const Colors = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  dim: "\x1b[2m",
  underscore: "\x1b[4m",
  blink: "\x1b[5m",
  reverse: "\x1b[7m",
  hidden: "\x1b[8m",
  bold: "\x1b[1m",
  black: "\x1b[30m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  magenta: "\x1b[35m",
  cyan: "\x1b[36m",
  white: "\x1b[37m",
};

export const colorize = {
  red: (text) => `${Colors.red}${text}${Colors.reset}`,
  green: (text) => `${Colors.green}${text}${Colors.reset}`,
  yellow: (text) => `${Colors.yellow}${text}${Colors.reset}`,
  blue: (text) => `${Colors.blue}${text}${Colors.reset}`,
  magenta: (text) => `${Colors.magenta}${text}${Colors.reset}`,
  cyan: (text) => `${Colors.cyan}${text}${Colors.reset}`,
  white: (text) => `${Colors.white}${text}${Colors.reset}`,
  bold: (text) => `${Colors.bold}${text}${Colors.reset}`,
  bright: (text) => `${Colors.bright}${text}${Colors.reset}`,
  dim: (text) => `${Colors.dim}${text}${Colors.reset}`,
  underscore: (text) => `${Colors.underscore}${text}${Colors.reset}`,
  blink: (text) => `${Colors.blink}${text}${Colors.reset}`,
  reverse: (text) => `${Colors.reverse}${text}${Colors.reset}`,
  hidden: (text) => `${Colors.hidden}${text}${Colors.reset}`,
};
